# Generated by Django 4.0.3 on 2022-03-29 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LanguageLevels',
            new_name='LanguageLevel',
        ),
    ]
