# Generated by Django 4.0.3 on 2022-04-03 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_rename_languagelevels_languagelevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.country'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='native_in',
            field=models.ManyToManyField(blank=True, null=True, related_name='native', to='mainapp.language'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='study',
            field=models.ManyToManyField(blank=True, null=True, through='mainapp.LanguageLevel', to='mainapp.language'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='mainapp.tag'),
        ),
    ]
