# Generated by Django 4.0.3 on 2022-04-04 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_profile_country_alter_profile_native_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='native_in',
            field=models.ManyToManyField(blank=True, related_name='native', to='mainapp.language'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='study',
            field=models.ManyToManyField(blank=True, through='mainapp.LanguageLevel', to='mainapp.language'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tags',
            field=models.ManyToManyField(blank=True, to='mainapp.tag'),
        ),
    ]
