# Generated by Django 4.0.3 on 2022-04-07 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_profile_native_in_alter_profile_study_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-user__last_login']},
        ),
    ]
