# Generated by Django 4.0.3 on 2022-04-08 07:29

from django.db import migrations


def add_data_to_db(apps, schema_editor):
    TagsArea = apps.get_model('mainapp', 'TagsArea')
    TagsArea.objects.create(area='RAP music')
    TagsArea.objects.create(area='Rock music')


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_profile_options'),
    ]

    operations = [
        migrations.RunPython(add_data_to_db, lambda x,y: None)
    ]
