# Generated by Django 4.0.3 on 2022-04-17 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_CUSTOM'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateField(auto_now_add=True)),
                ('response_date', models.DateField(blank=True)),
                ('profile1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='following', to='mainapp.profile')),
                ('profile2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='follower', to='mainapp.profile')),
            ],
        ),
    ]
