# Generated by Django 4.0.3 on 2022-04-17 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_partner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partner',
            old_name='profile2',
            new_name='follower',
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='profile1',
            new_name='following',
        ),
    ]
