# Generated by Django 4.0.3 on 2022-04-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_rename_profile2_partner_follower_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='response_date',
            field=models.DateField(null=True),
        ),
    ]
