# Generated by Django 4.0.3 on 2022-04-19 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_alter_partner_response_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='request_date',
            field=models.DateField(auto_now=True),
        ),
    ]
