# Generated by Django 4.0.3 on 2022-04-20 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_alter_partner_request_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partner',
            old_name='following',
            new_name='followed',
        ),
    ]
