# Generated by Django 4.0.3 on 2022-04-20 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_alter_partner_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='partner',
            unique_together={('followed', 'follower')},
        ),
    ]
